development:
  adapter: postgresql
  encoding: unicode
  database: dev
  pool: 5
  username: JLV
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: JLV
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: prod
  pool: 5
  username: JLV
  password:
